name: Build App
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches: ["master", "main"]
env:
  APP_NAME: "kook"
  URL: "https://www.kookapp.cn/app/login"
  WIDTH: "1200"
  HEIGHT: "780"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Install pake-cli local
        shell: bash
        run: |
          echo "install pake on local"
          pnpm install -g pake-cli
          pake https://www.kookapp.cn/app/login --name KOOK --width 1200 --height 800 --hide-title-bar

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: './*exe'
  release:
    name: Release
    needs: [compile]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Merge binaries
        uses: actions/upload-artifact/merge@v4
        with:
          name: binaries
          pattern: '*'
          retention-days: 1

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: ./packages

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'packages/*'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          prerelease: true
          removeArtifacts: true
          allowUpdates: true
